# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "v*.*.*"

permissions: read-all

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
      id-token: write
      # issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bolt
        uses: koalalab-inc/bolt@98e1363730b62fc8d3aa5a9a8e5605f875573851 # koalalab-inc/bolt@v1 | v1.0.0
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3 | v3.6.0
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags
      - name: GHCR login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # docker/login-action@v3 | v3.0.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # actions/setup-go@v4 | v4.1.0
        with:
          go-version: 1.21.4
      - name: Setup Cosign
        uses: sigstore/cosign-installer@1fc5bd396d372bee37d608f955b336615edf79c8 # sigstore/cosign-installer@v3.2.0 | main
      - name: Set version to github tag name
        uses: mikefarah/yq@9adde1ac14bb283b8955d2b0d567bcaf3c69e639 # mikefarah/yq@v4.42.1 | v4
        with:
          cmd: yq -i '.version |= "${{ github.ref_name }}"' .goreleaser.yml
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # goreleaser/goreleaser-action@v5 | v5.0.0
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
